[platformio]
default_envs = tester

[env:tester]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DROLE_TESTER

[env:mock_ecu]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DROLE_MOCK_ECU
